### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by alwayz123** [HacksNextDoor/always123#12]
[Parent_Handbook.pdf](https://github.com/hacksnextdoor/always123/files/1024296/Parent_Handbook.pdf)
[Registration_packet.pdf](https://github.com/hacksnextdoor/always123/files/1024298/Registration_packet.pdf)
[supply list.pdf](https://github.com/hacksnextdoor/always123/files/1024299/supply.list.pdf)

**Comment by hxghhhh** [comment]
Added [Forms](http://always123.com/views/forms.html)
